import Head from "next/head";

import { Footer, HeroSection, Navbar } from "../components";
import { client, urlFor } from "../libs/client";

const Home = ({ productData, bannderData }) => (
  <div className="">
    <Head>
      <title>Designer</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="">
      <Navbar />
      <HeroSection />

      <div>{console.log(productData)}</div>
      <Footer />
    </div>
  </div>
);

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const queryBanner = '*[_type == "banner"]';

  const productData = await client.fetch(query);
  const bannderData = await client.fetch(queryBanner);

  return {
    props: {
      productData,
      bannderData,
    },
  };
};

export default Home;
